name: my_portfolio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 700
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 800
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 300
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 500
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 600
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 100
    - family: SansPro
      fonts:
        - asset: assets/fonts/SansPro-Regular.ttf
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 700
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 800
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 300
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 600
        - asset: assets/fonts/SansPro-Regular.ttf
          weight: 100

